[question_initial]
message = """### Hello! Welcome to CodeDuos's HR Processes Optimizer.

Please provide the job description so that we can proceed with the next step.

Let's proceed!"""

[question_skills_weight]
message = "Please enter the list of {length} weights as a comma separated list, like e.g: `4, 3, 2, 1, 1` for the skills below.  \n\n- {skills}"

[question_upload_file]
message = "Please upload multiple pdf files with the CV of a candidate!"

[update_file_message]
message = "### Processing \n\n- {file_names}. \n\nYou have currently **{length}** files.\n\n"

[error_skills_weight]
message = "The length of the skill and weights do not match. Please make sure that the length of the skills and weights match, so that we can score the CVs."

[promt_skills]
prompt="""
Based on the following text, how many years does this person have in {technology}.? And tell whether this person has experience in {technology}. If a person has experience in {technology} but you cannot figure out the years reply with 1.\n\n
"""

